# Generated by Django 5.0.6 on 2026-07-04 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('leads', '0002_lead_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('chat_started', 'Chat Started'), ('message_sent', 'Message Sent'), ('lead_created', 'Lead Created'), ('lead_qualified', 'Lead Qualified'), ('lead_converted', 'Lead Converted'), ('lead_lost', 'Lead Lost'), ('email_notification_sent', 'Email Notification Sent')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chatbot.conversationsession')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leads.lead')),
            ],
        ),
    ]
