# Generated by Django 5.0.14 on 2026-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('chat_started', 'Chat Started'), ('message_sent', 'Message Sent'), ('lead_created', 'Lead Created'), ('lead_qualified', 'Lead Qualified'), ('lead_converted', 'Lead Converted'), ('lead_lost', 'Lead Lost'), ('email_notification_sent', 'Email Notification Sent'), ('scope_refusal', 'Scope Refusal'), ('escalation_triggered', 'Escalation Triggered'), ('feedback_submitted', 'Feedback Submitted'), ('llm_call', 'LLM Call'), ('lead_field_captured', 'Lead Field Captured'), ('chat_error', 'Chat Error')], max_length=50),
        ),
    ]
