# Generated by Django 5.0.1 on 2026-07-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsevent_occurred_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'permissions': [('view_analytics', 'Can view general analytics'), ('export_analytics', 'Can export analytics data'), ('view_sensitive_metrics', 'Can view sensitive metrics (revenue, conversions, emails)')]},
        ),
    ]
