# Generated by Django 5.0.1 on 2026-07-17 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('NOTICE', 'Notice'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('CRM', 'CRM'), ('LEADS', 'Leads'), ('KNOWLEDGE', 'Knowledge'), ('USERS', 'Users'), ('ROLES', 'Roles'), ('SETTINGS', 'Settings'), ('ANALYTICS', 'Analytics'), ('AI', 'AI'), ('AUTHENTICATION', 'Authentication'), ('DEPLOYMENT', 'Deployment'), ('SECURITY', 'Security')], default='SYSTEM', max_length=20)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_actor', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
