# Generated by Django 5.0.14 on 2026-07-12 18:47

from django.db import migrations


DEFAULT_CATEGORIES = {
    "company": {"name": "Company Info", "color": "#3b82f6"},
    "service": {"name": "Service", "color": "#10b981"},
    "industry": {"name": "Industry", "color": "#6366f1"},
    "faq": {"name": "FAQ", "color": "#f59e0b"},
    "contact": {"name": "Contact Info", "color": "#ec4899"},
    "technology": {"name": "Technology", "color": "#8b5cf6"},
    "general": {"name": "General", "color": "#64748b"},
}

def migrate_categories_forward(apps, schema_editor):
    KnowledgeEntry = apps.get_model('knowledge_base', 'KnowledgeEntry')
    Category = apps.get_model('knowledge_base', 'Category')

    for entry in KnowledgeEntry.objects.all():
        cat_str = entry.category
        if not cat_str:
            cat_str = 'general'
            
        defaults = DEFAULT_CATEGORIES.get(cat_str, {"name": cat_str.title(), "color": "#64748b"})
        
        category_obj, created = Category.objects.get_or_create(
            slug=cat_str,
            defaults={
                'name': defaults['name'],
                'color': defaults['color']
            }
        )
        entry.category_relation = category_obj
        entry.save(update_fields=['category_relation'])


def migrate_categories_backward(apps, schema_editor):
    KnowledgeEntry = apps.get_model('knowledge_base', 'KnowledgeEntry')
    for entry in KnowledgeEntry.objects.all():
        if entry.category_relation:
            entry.category = entry.category_relation.slug
            entry.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_category_tag_knowledgeentry_category_relation_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_categories_forward, migrate_categories_backward),
    ]

