# Generated by Django 5.0.14 on 2026-07-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_auto_20260713_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeentry',
            name='category_relation',
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='knowledge_base.category'),
        ),
    ]
