# Generated by Django 5.0.14 on 2026-07-13 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_remove_knowledgeentry_category_relation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(max_length=20)),
                ('category_snapshot', models.JSONField(blank=True, default=dict)),
                ('tags_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(default='No summary provided', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_versions_created', to=settings.AUTH_USER_MODEL)),
                ('knowledge_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_base.knowledgeentry')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('knowledge_entry', 'version_number')},
            },
        ),
    ]
