# Generated by Django 5.0.14 on 2026-07-15 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('GENERAL', 'General'), ('AI', 'AI'), ('CRM', 'CRM'), ('KNOWLEDGE_BASE', 'Knowledge Base'), ('ANALYTICS', 'Analytics'), ('NOTIFICATIONS', 'Notifications'), ('EMAIL', 'Email'), ('SECURITY', 'Security'), ('FEATURES', 'Features'), ('APPEARANCE', 'Appearance'), ('MAINTENANCE', 'Maintenance')], max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('FLOAT', 'Float'), ('JSON', 'JSON'), ('EMAIL', 'Email'), ('URL', 'URL')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'display_order', 'key'],
                'permissions': [('can_view_settings', 'Can View Settings'), ('can_change_settings', 'Can Change Settings'), ('can_initialize_settings', 'Can Initialize Settings')],
                'indexes': [models.Index(fields=['group'], name='platform_se_group_461e1e_idx'), models.Index(fields=['key'], name='platform_se_key_e9349a_idx'), models.Index(fields=['is_public'], name='platform_se_is_publ_d83980_idx')],
                'unique_together': {('group', 'key')},
            },
        ),
    ]
