# Generated by Django 5.0.14 on 2026-07-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action type identifier', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the change')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible data: IP, user agent, old/new values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='User who was acted upon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='user_manage_target__f2d2cb_idx'), models.Index(fields=['actor', '-created_at'], name='user_manage_actor_i_65cfc1_idx'), models.Index(fields=['action'], name='user_manage_action_2859bc_idx'), models.Index(fields=['-created_at'], name='user_manage_created_bdb0e1_idx')],
            },
        ),
    ]
