# Generated by Django 5.0.6 on 2026-07-03 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gathering', 'Gathering'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('escalated', 'Escalated'), ('converted', 'Converted'), ('lost', 'Lost')], default='gathering', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='chatbot.conversationsession')),
            ],
        ),
    ]
