# Generated by Django 5.0.14 on 2026-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
