# Generated by Django 5.0.14 on 2026-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_assigned_admin_id_lead_crm_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
