# Generated by Django 5.0.14 on 2026-07-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_qualified_at_last_contacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
