# Generated by Django 5.0.1 on 2026-07-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_admin_id',
            new_name='assigned_admin_uuid',
        ),
    ]
