# Generated by Django 5.0.1 on 2026-07-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_assigned_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_admin_uuid',
        ),
    ]
