# Generated by Django 5.0.1 on 2026-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_lead_assigned_admin_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('website_contact_form', 'Website Contact Form'), ('manual', 'Manual'), ('api', 'API'), ('website_service_request', 'Website Service Request'), ('website_book_meeting', 'Website Book Meeting'), ('website_partnership', 'Website Partnership'), ('website_careers', 'Website Careers')], default='chatbot', max_length=50),
        ),
    ]
