# Generated by Django 5.0.1 on 2026-07-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_feedback_conversationsession_channel_and_more'),
        ('leads', '0009_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='chatbot.conversationsession'),
        ),
    ]
