# Generated by Django 5.0.14 on 2026-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_qualified', 'Lead Qualified'), ('email_sent', 'Email Sent'), ('status_changed', 'Status Changed'), ('followup_created', 'Follow-up Created'), ('followup_completed', 'Follow-up Completed'), ('note_added', 'Note Added'), ('assignment', 'Assignment')], max_length=50),
        ),
    ]
