# Generated by Django 5.0.14 on 2026-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_leadactivity_activity_type'),
        ('leads', '0005_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('demo', 'Demo'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['lead', 'status'], name='crm_leadfol_lead_id_4ddca3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['scheduled_at'], name='crm_leadfol_schedul_ee8c41_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['followup_type'], name='crm_leadfol_followu_ca0c6e_idx'),
        ),
    ]
