# Generated by Django 5.0.14 on 2026-07-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('BRANDING', 'Branding'), ('AI', 'AI'), ('CHATBOT', 'Chatbot'), ('NOTIFICATIONS', 'Notifications'), ('SECURITY', 'Security'), ('FEATURE_FLAGS', 'Feature Flags'), ('INTEGRATIONS', 'Integrations')], max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='settings_ma_categor_6bd96a_idx'), models.Index(fields=['category', 'key'], name='settings_ma_categor_8782a1_idx'), models.Index(fields=['is_public'], name='settings_ma_is_publ_eeaaed_idx')],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
