# Generated by Django 5.0.14 on 2026-07-06 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_message_sequence_numbers(apps, schema_editor):
    Message = apps.get_model('chatbot', 'Message')
    ConversationSession = apps.get_model('chatbot', 'ConversationSession')
    for session in ConversationSession.objects.all().iterator():
        messages = Message.objects.filter(session=session).order_by('created_at', 'id')
        for index, message in enumerate(messages, start=1):
            if message.sequence_number is None:
                message.sequence_number = index
                message.save(update_fields=['sequence_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='channel',
            field=models.CharField(choices=[('web_widget', 'Web Widget'), ('api', 'API'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='web_widget', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='locale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='qualification_state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('gathering', 'Gathering'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('escalated_to_human', 'Escalated To Human')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick Reply'), ('card', 'Card'), ('form', 'Form'), ('system_event', 'System Event')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='response_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='token_count_input',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='token_count_output',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
        migrations.RunPython(backfill_message_sequence_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('session', 'sequence_number'), name='uq_message_session_sequence'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.message'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.conversationsession'),
        ),
    ]
